##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/grapa
    - autoconf-archive
    - automake
    - caja
    - clang
    - file
    - gcc
    - g++
    - gettext
    - git
    - gtk3
    - libtool
    - json-glib
    - make
    - pkgconf
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/grapa
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gettext
    - gcc
    - g++
    - git
    - libcaja-extension-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjson-glib-dev
    - libmagic-dev
    - libtool
    - make
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/grapa.git
    - autoconf-archive
    - caja-devel
    - clang
    - clang-analyzer
    - desktop-file-utils
    - file-devel
    - gcc
    - g++
    - gettext-devel
    - git
    - gtk3-devel
    - json-glib-devel
    - libSM-devel
    - libtool
    - make
    - redhat-rpm-config
    - yelp-tools

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gcc
    - g++
    - gettext
    - git
    - libcaja-extension-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjson-glib-dev
    - libmagic-dev
    - libtool
    - make
    - yelp-tools

before_scripts:
   # Install cafe-common from master branch
  - cd ${START_DIR}
  - git clone --depth 1  https://github.com/cafe-desktop/cafe-common.git -b master cafe-common-master
  - cd cafe-common-master
  - ./autogen.sh
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  #- NOCONFIGURE=1 ./autogen.sh
  - export CXXFLAGS+=" -std=c++17"
#  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $(( $CPU_COUNT + 1 ))
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: grapa-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.cafe-desktop.org/release

